#!bin/bash
IPs=$(ifconfig | awk '/inet addr/{print substr($2,6)}' )
firstIP=$(echo $IPs | awk '{print $1}')
secondIP=$(echo $IPs | awk '{print $}')
if [[ $firstIP == 127* ]]; then
  echo "Local IP"
elif [[ $firstIP == 10* || $firstIP == 192.168* ]]; then
  echo "Private IP"
else
  echo "Public IP"
fi
